export const locations = [
    {
        name: "Golden Gate Bridge",
        city: "San Francisco",
        latitude: 37.8199,
        longitude: -122.4783,
        province: "CA",
    },
    {
        name: "Simon Fraser University",
        city: "Burnaby",
        latitude: 49.279063,
        longitude: -122.91754900000001,
        province: "BC",
    },
    {
        name: "UBC Rose Garden",
        city: "Burnaby",
        latitude: 49.269165,
        longitude: -123.256381,
        province: "BC",
    },
    {
        name: "The Metropolitan Museum of Art",
        city: "New York",
        latitude: 40.7794,
        longitude: -73.9632,
        province: "NY",
    },
    {
        name: "Jollibee",
        city: "Winnipeg",
        latitude: 49.9410,
        longitude: -97.1570,
        province: "MB",
    },
    {
        name: "Canada Place",
        city: "Vancouver",
        latitude: 49.2888,
        longitude: -123.1111,
        province: "BC",
    },
    {
        name: "Hanauma Bay",
        city: "Honolulu",
        latitude: 21.2690,
        longitude: -157.6938,
        province: "Hawaii",
    },
    {
        name: "Moraine Lake",
        city: "Banff",
        latitude: 51.3217,
        longitude: -116.1860,
        province: "AB",
    },
    {
        name: "Niagara Falls Centre",
        city: "Niagara Falls",
        latitude: 43.0896,
        longitude: -79.0849,
        province: "ON",
    },
    {
        name: "McGill University",
        city: "Montreal",
        latitude: 45.5048,
        longitude: -73.5772,
        province: "Quebec",
    }
]